### ISSUE TITLE
docker images build hides bindings problems

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-ci#2]
This currently hides errors in buildings bindings
```
${SRC_DCTRL} ${BLD} bexec "${BUILD_CMD} bindings || echo no bindings" && foo
```

My idea was to use sth along the line of
```
${SRC_DCTRL} ${BLD} bexec "${BUILD_CMD} bindings || grep 'unknown target' " && foo
```

but dunecontrol/docker does weird escaping there, plus subshell didn't work with dunecontrol, so I gave up again. 

Code is in https://github.com/dune-community/dune-xt-ci/blob/master/docker/individual_base/Dockerfile#L16
and is triggered from https://github.com/dune-community/dune-xt-ci/blob/master/docker/update_test_dockers.py for example in gdt CI

```
cd dune-gdt-super
./.ci/shared/update_test_dockers.py BASE
./.ci/shared/update_test_dockers.py dune-gdt
```

**Comment by ftalbrecht** [comment]
I guess we should adapt the `Dockerfile` to act according to `MY_MODULE`: we know that the bindings target is only there in xt and gdt and that the script is either used for xt or gdt: we can thus unconditionally build the xt bindungs and in addition the gdt bindings if `MY_MODULE==dune-gdt`.

**Comment by ftalbrecht** [comment]
I was thinking of something like

```
... \
${SRC_DCTRL} ${BLD} --only=dune-xt bexec "${BUILD_CMD} bindings" && \
([ "X$MY_MODULE" == "X" ] || ${SRC_DCTRL} ${BLD} --only=dune-gdt bexec "${BUILD_CMD} bindings") \
...
```

though I am unsure if the `||` works as intended due to the concatenation with the other `&&`. Maybe simply have this in separate `RUN` directives?

**Comment by ftalbrecht** [comment]
the dune-gdt-super went through, though?

**Comment by renefritze** [comment]
> the dune-gdt-super went through, though?

That was indeed unrelated to this issue.


> though I am unsure if the `||` works as intended due to the concatenation with the other `&&`. 

That's not an issue. For me dunecontrol hung indefinitely only when I tried to pass the bexec subcommand a subshell.

> Maybe simply have this in separate `RUN` directives?

Is automatic building of dependent bindings currently default enabled? If yes, we could actually always just call

`${SRC_DCTRL} ${BLD} --only=${MY_MODULE} bexec "${BUILD_CMD} bindings"` unconditionally.

**Comment by ftalbrecht** [comment]
> Is automatic building of dependent bindings currently default enabled? If yes, we could actually always just call
> 
> `${SRC_DCTRL} ${BLD} --only=${MY_MODULE} bexec "${BUILD_CMD} bindings"` unconditionally.

With the `bindings` target it is, yes. So lets just do that for the moment.

As a side note: I find this unintuitive, since it does not match the other targets behaviours (`all` does not rebuild the other dune modules, although we depend on their libraries) and I propose to

* drop `bindings`
* rename `bindings_no_ext` to `all_python`

which I already mentioned offline some time ago. We would then have `all_python` and `install_python`, which would behave like `all` and `install`; but that is a separate issue for later...

**Comment by renefritze** [comment]
Hmm, if I understood you correctly we'd end up having no target that compiles dependent bindings targets? 
I'm fine with renaming to bring it more in line with others, but I'd like to have the option with all deps (don't care how it's called).

**Comment by renefritze** [comment]
This is now obsolete
