### ISSUE TITLE
update python targets in dune-xt and dune-gdt

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-ci#3]
see my comment in #2

**Comment by ftalbrecht** [comment]
Something like:

* `bindings_no_ext` -> `all_python`
* `install_???` -> `install_python` (nbot sure how the current target is called)
* `bindings` -> `all_python_with_deps`

@renefritze ?

Should we then also have

* `install_python_with_deps`?

Note that the `_with_deps` targets only make sense in `dune-gdt` by now...

**Comment by renefritze** [comment]
Sounds good :+1: 

> Note that the `_with_deps` targets only make sense in `dune-gdt` by now...

There's at least one module that has gdt has a dependency :wink:

**Comment by renefritze** [comment]
Also obsolete
